use_frameworks!

platform :ios, '9.0'

target 'ConsoliadsPod_Example' do
  pod 'ConsoliadsPod', :path => '../'

  target 'ConsoliadsPod_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
